### ISSUE TITLE
Subsonic SSL behind Reverse Proxy - Settings doesn't work

### ISSUE THREAD

**Issue by stevesbrain** [hurricanehrndz/docker-containers#10]
Hey there,

Got subsonic container running, default port 4040, plaintext only. Putting it behind HAProxy reverse proxy letting that handle SSL. I can login + stream fine, but trying to go to settings doesn't work (just doesn't load anything), and when doing actions like adding or deleting podcast, page doesn't show anything (however actions get executed - i.e. if I browse away from podcasts page and back to it, it has been added).

Plaintext/port 80 behind HAProxy works flawlessly however. I hope it's not required to have the docker VM itself doing HTTPS as well, as that'd end up with double-stacking HTTPS which I'd rather not do (less overhead). Any suggestions would be appreciated :)

**Comment by stevesbrain** [comment]
Any word on this? Been open for a while :)

**Comment by hurricanehrndz** [comment]
@stevesbrain 

I 'm sorry for the late response. Unfortunately,  I can not address or fix the issue, since the issue doesn't relate to the actual container itself, but rather how you have configured the proxy. That being said, I did some searching for you, and I believe the following link might be of help:

https://github.com/fxthomas/libresonic/blob/31762a3e50015eddee2cffe2d7a1cd97d373c051/documentation/PROXY.md

Although the above link refers to libresonic, remember that libresonic is a fork of subsonic. Although some of the details may differ, it might help you get a a better a idea of where your config for HAProxy has gone wrong. 

Please review the docker environment variables as well. they might have an affect on the proxy. Specifically the context path. Best of luck. I'm closing this issue since there is not much I can do on my end.

**Comment by stevesbrain** [comment]
No worries @hurricanehrndz - thanks for clarifying that this isn't an issue with this project. I'd thought it may be just due to the fact similar configs with all my other containers were fine. Appreciate the response, and thanks for taking the time to research some possible solutions as well. I'll definitely check them out - have a great day :)

**Comment by brokencube** [comment]
The problem seems to be that Subsonic seems to try and request that particular page via http instead of https - I have the same problem and I see this error in the js console:
```
Mixed Content: The page at 'https://music.brokencube.co.uk/index.view' was loaded over HTTPS, but requested an insecure resource 'http://music.brokencube.co.uk/musicFolderSettings.view'. This request has been blocked; the content must be served over HTTPS.
```
If you go to the link directly, it properly redirects to the SSL version of the page (301 redirect to HTTPS).
