### ISSUE TITLE
Allow custom encoders in subsonic

### ISSUE THREAD

**Issue by neersighted** [hurricanehrndz/docker-containers#2]
It would be nice if /subsonic/transcode was not clobbered, in order to allow installation of custom encoders (opusenc/oggenc), or a ffmpeg binary linked to libopus/libvorbis. In fact, adding a way to install additional codecs (so ffmpeg could handle ogg/opus duties) would be a nice bonus.

**Comment by hurricanehrndz** [comment]
ffmpeg in the transcode folder is linked to the system installed version of ffmpeg. This is done in order to support more codecs out of the box. Have you tried to play ogg? I did this specifically because I have friend who has flac files and likes them to play out of the box. You should be able to install additional codecs by running a simple docker exec command such as

```
docker exec zypper in codec-name
```

Can you please expand on what you mean by clobbered?

**Comment by hurricanehrndz** [comment]
I think I know what you mean, you wish for me not to clear the directory each time upon creation of the directory. Am I understanding you correctly?

**Comment by neersighted** [comment]
Yeah, it would be nice if the folder was not cleared. Also, libogg appears to be installed but not libopus.

**Comment by hurricanehrndz** [comment]
Okay, I will make it possible

**Comment by hurricanehrndz** [comment]
@neersighted Can you do me a favour and check if installing libopus fixes the issues for you.

**Comment by neersighted** [comment]
Using a binary statically compiled against libopus works; I cannot get zypper to install libopus in the container as it hangs on the repo update for some reason.

**Comment by hurricanehrndz** [comment]
Okay good, to know. I will make it so that the transcode directory does not get
deleted.
On Tue, Apr 19, 2016 at 11:21:33AM -0700, Bjorn Neergaard wrote:
> Using a binary statically compiled against libopus works; I cannot get zypper to install libopus in the container as it hangs on the repo update for some reason.
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/hurricanehrndz/docker-containers/issues/2#issuecomment-212054400

-- 
Best Regards,
Carlos Hernandez
4096R / 7E40 E100 C53B 0F20 0A80  E02A D46C 6686 45CE FC3F
https://sks-keyservers.net/pks/lookup?op=get&search=0x45CEFC3F
